#spring:
#  config:
#    activate:
#      on-profile: windows
#---
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
#  config:
#    activate:
#      on-profile: windows
  datasource:
    url: jdbc:mysql://localhost:3306/glimmer_index?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    password: qmqebiqmlszujacg
    host: smtp.qq.com
    username: antio2@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
#  redis:
#    password: 123456