spring:
  config:
    activate:
      on-profile: windows
---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: windows
  datasource:
    dynamic:

    url: jdbc:mysql://localhost:3306/glimmer_index?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: localhost
#      password: 123456
#      port: 6379


---